{DTP}
[advantages and disadvantages of DTP software]
font: Times New Roman;
Font-size: 12;
document-type: PDF;
{COMPUTERS APPLICATIONS}
[DISCUSS COMPUTERS IN TERM OF THE FOLLOWING]
size: CHARACHTERISTICS, ADVANTAGES & DIASDVANTAGES
GENERATION: CHARACHTERISTICS, ADVANTAGES & DIASDVANTAGES
PURPOSE: CHARACHTERISTICS, ADVANTAGES & DIASDVANTAGES
MODE OF OPERATION: CHARACHTERISTICS, ADVANTAGES & DIASDVANTAGES

[DISCUSS PROCESSOR COMPONENTS]
CHARACHTERISTICS
FUNCTIONS

[DICUSS TYPES OF REGISTERS]

[COMMUNICATION SKILLS]

[ADVANTAGES / DIASDVANTAGES OF GRAPEVINE INTERACTION]
 /* AT LEAST 10 OF EACH */
