[COMMUNICATION PROCESS]


SENDER------->MEDIA-------->RECEIVER
                                |
                                |
____________ FEEDBACK_________ |

    [SENDER]
    ->THIS IS THE PERSON WHO CONCIEVES AND TRANSMITTS THE MESSAGE.
        ->MESSAGES CAN BE VERBAL AND ALSO NON-VERBAL.
    [ENCODING]
    ->PUTTING THE MESSAGE INTO APPROPRIATE WORDS OR NON-VERBAL METHODS.
    [CHANNEL/MEDIA]
    ->METHOD USED TO DELIVER THE MESSAGE EG PHONE CALLS, MEMOS, MESSAGES ETC.
    [DECODING]
    ->ATTACHING A MEANING TO THE WORDS/SYMBOLS BY THE RECEIVER.
    [RECEIVER]
    THE PERSON RECEIVING THE MESSAGE
    [FEEDBACK]
    THE RESPONSE GIVEN BY THE RECEIVER TO THE SENDER OF THE MESSAGE EG 
    [NOISE]
    ANY INTERFERANCE DURING THE EXCHANGE OF THE MESSAGE
        ->PHYSICAL/EXTERNAL
        ->PHYSIOLOGICAL

[EFFECTIVE COMMUNICATION]
/*THE 7 C's */
 ->COMPLETENESS {GIVING NECESSARY INFO}, SENDING THE WHOLE MESSAGE.
 ->CONCISENESS /* THE WORDS MUST CONVEY ONLY ONE POSSIBLE MEANING */
 ->CONSIDERATION /* STEPPING INTO THE OTHER PERSON'S SHOES */
 ->CLARITY /* EMPHASIZING ON A SPECIFIC MESSAGE OR GOAL */ BE CLEAR
 ->CONCRETENESS /* THIS IS ENSURING THE MESSAGE HAS SOME WEIGHT, IT HAS FACTS AND FIGURES*/
 ->CORRECTNESS /* DO NOT LIE */
 ->CURTESY /* EXPRESSING RESPECT TO THE RECIEVER */ BE POSITIVE AND FOCUSED ABOUT YOUR AUDIENCE

[GUIDELINES ON COMMUNICATION IN A BUSINESS]
-> FEEDBACK /* ALWAYS REPORT BACK TO THE PERSON WHO SENT YOU THE MESSAGE */
-> EMPATHY /*PUTTING YOURSELF IN THE OTHER PERSONS'S SHOES */
-> MODIFY THE MESSAGE ACCORDING TO THE AUDIENCE
-> HAVE MULTIPLE CHANNELS OF COMMUNICATION
[BARRIERS OF COMMUNICATION]
-> LANGUAGE/PERCEPTUAL /* PRONUNCIATIONS, 
->INFORMATION OVERLOAD /*
-> INATTENTION
-> TIME PRESSURES
-> NOISE/DISTRACTIONS/LIGHTING/AIR/
->EMOTIONS
->POOR RETENTION 
->COMPLEXITY IN THE ORGANIZATIONAL STRUCTURE
[OVERCOMMING COMMUNICATION BARRIERS]
->ELIMINATE DIFFERENCES IN PERCEPTION
->USE SIMPLE LANGUAGE
->REDUCE OR ELIMINATE NOISE
->ACTIVE LISTENING /* LIFT YOUR HEAD & LISTENING, NODDING ALONG, EYE CONTACT ETC */
->CONSIDER YOUR EMOTIONAL STATE
->HAVE A SIMPLE ORGANIZATIONAL STRUCTURE
->AVOID INFORMATION OVERLOAD
->GIVE CONSTRUCTIVE FEEDBACK
->SELECT A PROPER CHANNEL OR MEDIA
->FLEXIBILTY IN MEETING OF TARGETS


[QUESTIONS]
YOU ARE A WORKING FOR A MULTINATIONAL COMPANY WITH OFFICES IN VARIOUS CONTINENTS IN THE WORLD.
 (a) EXPLAIN HOW THE ORGANIZATION SHOULD ENHANCE ITS COMMUNICATION USING AN APPROPRIATE COMMUNICATION DIAGRAM.
 (b) EXPLAIN VARIOUS BARRIERS OF COMMUNICATION FOR SUCH AN ORGANIZATION AND HOW TO ELIMINATE THEM.
            TIMEZONES HAVING FLEXIBLE WORKING HOURS OR ROUND THE CLOCK STAFF
            LANGUAGE
            COMPLEXITY IN THE ORGANIZATIONAL STRUCTURE

