[COMPUTER SOFTWARE]
[SOFTWARE]
/* IT IS APROGRAM THAT IS COMMERCIALLY PREPARED AND TESTED BY ONE OR A GROUP OF PROGRAMMERS AND/OR SYSTEM ANALYSTS TO PERFORM A SPECIFIC TASK */
/*SOFTWARE IS SIMPLY A SET OF INSTRUCTIONS THAT CAUSES A COMPUTER TO PERFORM ONE OR MORE TASKS */
    [SYSTEM SOFTWARE]
    /* IT IS A COLLECTION OF PROGRAMMES DESIGNED TO OPERATE, CONTROL AND EXTEND THE PROCESSING CAPABILITIES OF THE COMPUTER ITSELF */
    /* THESE SOFTWARES COMPRISE OF PROGRAMMES WRITTEN IN LOW-LEVEL LANGUAGES WHICH INTERACT WITH THE HARDWARE AT A VERY BASIC LEVEL. */
    /* THESE SYSTEM SOFTWARE SERVERS AS AN INTERFACE BTWN THE HARDWARE AND APPLICATION PROGRAMMES */
        [CLASSIFICATIONS OF SYSTEM SOFTWARE]
            [OPERATING SYSTEM]
            /* IT IS A COMPLEX PROGRAMME AND IT CONTROLS THE OPERATION OF A COMPUTER*/
            /* IT MANAGES THE COMPUTER HARDWARE AND CONTROLS THE ALLOCATION OF RESOURCES AND SERVICES */
            /* THE OS PERFORMS THE FOLLOWING 4 MAJOR FUNCTIONS */
                ->MEMORY MANAGEMENT
                ->PROCESS MANAGEMENT
                ->FILE MANAGEMENT
                ->DEVICE MANAGEMENT
            [EXAMPLES OF OPERATING SYSTEMS]
                ->WINDOWS NT
                -> MS-DOS
                ->UNIX
                ->MacOS
                ->LINUX

            [SERVICE PROGRAMMES]

            [UTILITIES]
                /* THESE ARE PROGRAMMES USEDTO MAINTAINING AND MANAGING A COMPUTER SYSTEM */
                /* THESE PROGRAMMES CAN BE PURCHASED AS STANDALONE PROGRAMMES OR EMBEDDED IN AN OPERATING SYSTEM */
                    [EXAMPLES OF UTILITIES]
                    ->ANTIVIRUS /* USED TO PROTECT YOUR COMPUTER FROM DAMAGE CAUSED BY VIRUSES AND MALICIOUS SOFTWARE */
                    ->COMPRESSION UTILITIES /* MAKES THE FILES SMALLER FOR STORAGE */
                    ->DATA RECOVERY /* IT ATTEMPTS TO RECOVER DATA THAT HAS BEEN DAMAGED OR DELETED */
                    ->SCREEN SAVERS /* USED TO DISPLAY A CONSTANTLY MOVING IMAGE WHENEVER THE SCREEN IS IDLE IN ORDER TO PREVENT SCREEN BURN IN COMMON IN CRT AND OLED DISPLAYS. */
                    ->UNINSTALLER /* USED TO REMOVE INSTALLED PROGRAMMES AND THEIR ASSOCIATED FILES */
                    ->BACKUP UTILITY /* USED TO COPY ALL OR SELECTED FILES FROM ONE DISK TO ANOTHER DISK FOR SAFEKEEPING */
                
                [DEVELOPMENT PROGRAMMES]
                /* USED TO TRANSLATE THE SOURCE PROGRAMME TO OBJECT PROGRAMME IN LOW LEVEL LANGUAGES THAT THE COMPUTER CAN EXECUTE */
                    [ASSEMBLER]
                    /* USED TO TRANSLATE THE SYMBOLIC INSTRUCTION CODE IN PROGRAMES WRITTEN IN AN ASSEMBLER LANGUAGE INTO MACHINE LANGUAGE INSTRUCTIONS */
                    [COMPILER]
                    /* USED TO COMPILE HIGH LEVEL LANGUAGE STATEMENTS  {SOURCE PROGRAMMES} TO MACHINE LANGUAGE PROGRAMMES */
                    [INTERPRETER]
                    /* THESE ARE PROGRAMMES USED TO TRANSLATE AND EXECUTE EACH PROGRAMME STATEMENT ONE AT A TIME INSTEAD OF FIRST PRODUCING A MACHINE LANGUAGE PROGRAMME*/

            [COMMUNICATION PROGRAMMES]
            /* PROGRAMMES THAT ENABLE US TO TRANSMIT DATA FROM ONE POINT TO ANOTHER */  
