[FEATURE OF A DTP]
	[GRAPHIC TOOLS]
	->The ability to edit images is also an absolute must for DTP software.
	->An ideal application should allow you to do more than just maninpulate 
	an image. (you can design/crop/compress an image).
	
	[PRINTING AND SHARING]
	->A piece of DTP software is supposed to be able to be shared either
	electronically or virtually.
