[FEATURE OF A DTP]
	[GRAPHIC TOOLS]
	->The ability to edit images is also an absolute must for DTP software.
	->An ideal application should allow you to do more than just maninpulate 
	an image. (you can design/crop/compress an image).
	
	[PRINTING AND SHARING]
	->A piece of DTP software is supposed to be able to be shared either
	electronically or virtually.

[USES OF DTP SOFTWARE]
->GRAPHIC DESIGN
	/*PROFFESIONAL GRAPHIC DESIGNERS USE DTP PROGRAMMES SUCH AS: {QuarkXpress, Ventura, Corel Draw, Framemaker, Apple pages etc} TO VISUALIZE THEIR DOCUMENTATION.

->CAREER ASSISTANCE
->EDUCATION
->BUSINESS
->CRAFTS AND PERSONAL PROJECTS

[PARTS OF A PUBLICATION]
->QUICK ACCESS TOOLBAR
	/* IT APPEARS ON THE LEFT SIDE OF THE TITLE BAR AND CONTAINS FREQUENTLY USED COMMANDSTHAT ARE INDEPENDENT FROM THOSE DISPLAYED ON THE LABEL */
->TITLE BAR
	/* APPEARS ON THE TOP OF THE PROGRAM WINDOW AND DISPLAYS THE NAME OF THE PUBLICATION AND THE PROGRAM */
	/* THE BUTTON ON THE RIGHT HAND SIDE ARE USED TO HELP AS WELL AS MINIMIZE, RESTORE,MAXIMIZE  AND CLOSE THE PROGRAM */
-> RIBBON
	/*THE RIBBON EXTENDS ACROSS AT THE TOP OF THE PROGRAM WINDOW AND CONSISTS OF A SET OF TABS EACH WITH SPECIFIC FEATURES AND NORMALLY GROUPED IN COMMANDS FEATURE*/
-> PAGES PANE
	/* APPEARS ON THE LEFT SIDE OF THE PROGRAM WINDOW AND DISPLAYS THUMBNAILS FOR EACH PAGE IN A PUBLICATION */
	/* THESE PAGE PANES CAN BE USED TO NAVIGATE TO A PARTICULAR PAGE BY JUST CLICKING ITS THUMBNAIL */
	/* TO REARRANGE PAGES BY CLICKING THE THUMBNAILS */
-> SCRATCH AREA
	/* THIS IS THE GREY AREA SURROUNDING THE PAGE, ACTS AS A HOLDING SPACE FOR ANY OBJECTS YOU MAY WANT TO PULL OF THE PAGE AND USE LATER */
-> WORKSPACE
 /* IT IS USED TO DISPLAY THE CONTENT OF YOUR CURRENT PAGE */
-> STATUS BAR
 /* IT APPEARS ON THE BOTTOM OF YOUR PROGRAM WINDOW AND DISPLAYS INFO ABOUT YOUR PUBLICATION (PAGE NUMBER, OBJECT POSITION & SIZE, TEXT ETC AND TOOL ON YOUR RIGHT SIDE OF YOUR STATUS BAR ARE USED TO ADJUST YOUR ZOOMING LEVEL OF YOUR WORK */
